-- 2026-05-28: Seed idempotente das 55 unidades escolares
-- Pode ser reaplicado sem duplicar, usando o INEP como chave unica.

insert into public.school_units (name, inep, type, district, manager_name)
values
  ('Escola M. Acelina Alves de Araújo', '52100001', 'escola', 'Camping Clube', 'Gestor(a) da Unidade 01'),
  ('Escola M. Ana Lúcia Oliveira da Silva', '52100002', 'escola', 'Jardim América II', 'Gestor(a) da Unidade 02'),
  ('Escola M. Antônio Cícero Araújo da Costa', '52100003', 'escola', 'Mansões Odisséia', 'Gestor(a) da Unidade 03'),
  ('Escola Municipal Antônio de Jesus Leite', '52100004', 'escola', 'Jardim Querência', 'Gestor(a) da Unidade 04'),
  ('Escola Municipal Antônio Luiz Gonzaga', '52100005', 'escola', 'Parque da Barragem Setor 11', 'Gestor(a) da Unidade 05'),
  ('Escola Municipal Camargo II', '52100006', 'escola', 'Zona Rural', 'Gestor(a) da Unidade 06'),
  ('Escola Municipal Darci Ribeiro', '52100007', 'escola', 'Parque da Barragem Setor 08', 'Gestor(a) da Unidade 07'),
  ('Escola M. Domingos Simão de Oliveira', '52100008', 'escola', 'Jardim América IV', 'Gestor(a) da Unidade 08'),
  ('Escola Municipal Edinaldo Pereira', '52100009', 'escola', 'Mansões Coimbra', 'Gestor(a) da Unidade 09'),
  ('Escola M. Ednalda Guedes de Souza', '52100010', 'escola', 'Parque Águas Bonitas I', 'Gestor(a) da Unidade 10'),
  ('Escola M. Ednalva Valdevino dos Santos', '52100011', 'escola', 'Jardim Santa Lúcia', 'Gestor(a) da Unidade 11'),
  ('Escola M. Emília Ferreira de Souza', '52100012', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 12'),
  ('Escola Municipal Erotides Dias da Costa', '52100013', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 13'),
  ('Escola M. Fernando Cunha Junior', '52100014', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 14'),
  ('Escola M. Francisca Ferreira da Silva', '52100015', 'escola', 'Jardim Barragem V', 'Gestor(a) da Unidade 15'),
  ('Escola M. Geracina Pereira da Silva', '52100016', 'escola', 'Parque da Barragem Setor 02', 'Gestor(a) da Unidade 16'),
  ('Escola M. Inácio Carneiro da Costa', '52100017', 'escola', 'Jardim Barragem II', 'Gestor(a) da Unidade 17'),
  ('Escola Municipal Jardim das Oliveiras', '52100018', 'escola', 'Jardim das Oliveiras', 'Gestor(a) da Unidade 18'),
  ('Escola M. João Elízio Lima Pessoa', '52100019', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 19'),
  ('Escola M. José A. de Araújo - Zé Chevrolet', '52100020', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 20'),
  ('Escola Municipal José Vitorino de Souza', '52100021', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 21'),
  ('Escola Municipal Juliana Eloy da Silva', '52100022', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 22'),
  ('Escola Municipal Luiza Tereza', '52100023', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 23'),
  ('Escola Municipal Maria de Fátima Alves', '52100024', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 24'),
  ('Escola M. Maria do Livramento Felipe', '52100025', 'escola', 'Quinta das Angélicas', 'Gestor(a) da Unidade 25'),
  ('Escola Municipal Maria José Costa Lima', '52100026', 'escola', 'Recreio Águas Lindas III', 'Gestor(a) da Unidade 26'),
  ('Escola M. Maria Machado de Matos', '52100027', 'escola', 'Jardim Guaíra', 'Gestor(a) da Unidade 27'),
  ('Escola Municipal Maristela Regina Neris', '52100028', 'escola', 'Jardim Pérola I', 'Gestor(a) da Unidade 28'),
  ('Escola M. Joaquim Pedro Gomes da Cruz', '52071561', 'escola', 'Mansões Village', 'Gestor(a) da Unidade 29'),
  ('Escola Municipal MEG-LUZ', '52100030', 'escola', 'Parque da Barragem Setor 03', 'Gestor(a) da Unidade 30'),
  ('Escola Municipal Mestre Zezito', '52100031', 'escola', 'Águas Bonitas I', 'Gestor(a) da Unidade 31'),
  ('Escola Municipal Milena Barbosa Gama', '52100032', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 32'),
  ('Escola M. Nilzon Periquito de Lima', '52100033', 'escola', 'Mansões Olinda', 'Gestor(a) da Unidade 33'),
  ('Escola M. Orlando Soares de Sousa', '52100034', 'escola', 'Camping Clube', 'Gestor(a) da Unidade 34'),
  ('Escola M. P. Edileuza de A. Cavalcante', '52100035', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 35'),
  ('Escola M. Profª. Erika Flávia Vieira de Souza', '52100036', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 36'),
  ('Escola Municipal Roberto Alves da Silva', '52100037', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 37'),
  ('Escola Municipal Rui Barbosa', '52100038', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 38'),
  ('Escola Municipal São Bartolomeu', '52100039', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 39'),
  ('Escola M. Senador Emival Ramos Caiado', '52100040', 'escola', 'Águas Lindas de Goiás', 'Gestor(a) da Unidade 40'),
  ('Escola M. Vereador Érico Souza Ferreira', '52100041', 'escola', 'Jardim Brasília', 'Gestor(a) da Unidade 41'),
  ('Escola M. Vicente de Paula Lisboa', '52100042', 'escola', 'Jardim Águas Lindas II', 'Gestor(a) da Unidade 42'),
  ('Escola Municipal Zélia Correa Cotrim', '52100043', 'escola', 'Recreio da Barragem', 'Gestor(a) da Unidade 43'),
  ('CEMEI - Centro Municipal de Educação Inclusiva', '52100044', 'cemei', 'Jardim Brasília', 'Gestor(a) da Unidade 44'),
  ('Creche M. Dona Mª Pires Perillo', '52100045', 'creche', 'Parque da Barragem Setor 08', 'Gestor(a) da Unidade 45'),
  ('Creche M. Indiara Carneiro Machado Lisboa', '52100046', 'creche', 'Jardim Santa Lúcia', 'Gestor(a) da Unidade 46'),
  ('Creche Municipal Prof. Fátima Enes Muniz', '52100047', 'creche', 'Jardim América II', 'Gestor(a) da Unidade 47'),
  ('Creche M. Jardim Brasília II', '52100048', 'creche', 'Jardim Brasília II', 'Gestor(a) da Unidade 48'),
  ('Creche Municipal Profª. Vilma Maria da Costa Araújo', '52100049', 'creche', 'Jardim Guaíra I', 'Gestor(a) da Unidade 49'),
  ('Creche Municipal Eliene Martins Braga', '52100050', 'creche', 'Residencial Jardim Paraíso', 'Gestor(a) da Unidade 50'),
  ('Creche Municipal Prof. Ivaldo Rodrigues Lima', '52100051', 'creche', 'Jardim Pérola I', 'Gestor(a) da Unidade 51'),
  ('Creche M. José Rodrigues Bezerra', '52100052', 'creche', 'Jardim Barragem VI', 'Gestor(a) da Unidade 52'),
  ('Creche M. Mundo Encantado', '52100053', 'creche', 'Jardim Brasília', 'Gestor(a) da Unidade 53'),
  ('Creche Municipal Prof. Luiz Antônio Gonçalves de Oliveira', '52100054', 'creche', 'Parque Águas Bonitas I', 'Gestor(a) da Unidade 54'),
  ('Creche M. Pr. Geraldo Evaristo dos Santos', '52100055', 'creche', 'Mansões Pôr do Sol', 'Gestor(a) da Unidade 55')
on conflict (inep) do update set
  name = excluded.name,
  type = excluded.type,
  district = excluded.district,
  manager_name = excluded.manager_name,
  active = true;
